from app.models.schemas import (
    Claim,
    Evidence,
    ResearchReport,
    Source,
)


class ReportRenderer:

    def render(
        self,
        report: ResearchReport,
        sources: list[Source] | None = None,
        claims: list[Claim] | None = None,
        evidence: list[Evidence] | None = None,
    ) -> str:

        sources = sources or []
        claims = claims or []
        evidence = evidence or []

        citation_map = self._build_citation_map(
            sources
        )

        lines = [
            f"# {report.title}",
            "",
            "## Executive Summary",
            "",
            report.executive_summary,
            "",
            "## Research Question",
            "",
            report.research_question,
            "",
            "## Methodology",
            "",
            report.methodology,
            "",
            "## Key Findings",
            "",
        ]

        # -----------------------------------------------------
        # Key Findings
        # -----------------------------------------------------

        for finding in report.key_findings:

            citation_numbers = []

            for claim_id in finding.claim_ids:

                claim = next(
                    (
                        claim
                        for claim in claims
                        if claim.id == claim_id
                    ),
                    None,
                )

                if claim is None:
                    continue

                citation_number = citation_map.get(
                    claim.source_id
                )

                if (
                    citation_number is not None
                    and citation_number
                    not in citation_numbers
                ):
                    citation_numbers.append(
                        citation_number
                    )

            citations = "".join(
                f"[{number}]"
                for number in citation_numbers
            )

            if citations:
                lines.append(
                    f"- {finding.statement} {citations}"
                )
            else:
                lines.append(
                    f"- {finding.statement}"
                )

        # -----------------------------------------------------
        # Evidence & Analysis
        # -----------------------------------------------------

        lines.extend(
            [
                "",
                "## Evidence & Analysis",
                "",
            ]
        )

        for item in report.evidence_analysis:

            lines.append(item)
            lines.append("")

        # -----------------------------------------------------
        # Limitations
        # -----------------------------------------------------

        lines.extend(
            [
                "## Limitations",
                "",
            ]
        )

        for limitation in report.limitations:

            lines.append(
                f"- {limitation}"
            )

        # -----------------------------------------------------
        # Conclusion
        # -----------------------------------------------------

        lines.extend(
            [
                "",
                "## Conclusion",
                "",
                report.conclusion,
                "",
                "## Sources",
                "",
            ]
        )

        # -----------------------------------------------------
        # Sources
        # -----------------------------------------------------

        if sources:

            for source in sources:

                citation_number = citation_map[
                    source.id
                ]

                lines.append(
                    f"[{citation_number}] "
                    f"{source.title} — "
                    f"{source.url}"
                )

        else:

            # Preserve sources generated by the
            # ReportAgent when no provenance data
            # is supplied.

            for index, source in enumerate(
                report.sources,
                start=1,
            ):

                lines.append(
                    f"[{index}] {source}"
                )

        return "\n".join(lines)

    @staticmethod
    def _build_citation_map(
        sources: list[Source],
    ) -> dict[str, int]:

        return {
            source.id: index
            for index, source in enumerate(
                sources,
                start=1,
            )
        }

    @staticmethod
    def _find_citation(
        finding: str,
        claims: list[Claim],
        citation_map: dict[str, int],
    ) -> str:

        finding_lower = finding.lower()

        for claim in claims:

            claim_lower = (
                claim.statement.lower()
            )

            if (
                claim_lower in finding_lower
                or finding_lower in claim_lower
            ):

                citation_number = citation_map.get(
                    claim.source_id
                )

                if citation_number is not None:
                    return f"[{citation_number}]"

        return ""